fix error handling, disable master

diff --git a/.github/workflows/run-test.yml b/.github/workflows/run-test.yml
--- a/.github/workflows/run-test.yml
+++ b/.github/workflows/run-test.yml
@@ -11,7 +11,10 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        branch: ["master", "hobbyscoop", "old"]
+        branch:
+#          - master
+          - hobbyscoop
+          - old
     timeout-minutes: 60
     runs-on: ubuntu-latest
 
@@ -36,5 +39,5 @@ jobs:
         pip install -r requirements.txt
 
     - name: Run tests
-      run: BRANCH=${{ matrix.branch }} pytest || cat log && exit 1 # on error, show log and break
+      run: BRANCH=${{ matrix.branch }} pytest || (cat log && exit 1) # on error, show log and break
 
