fix test setup; add html

diff --git a/.github/workflows/run-test.yml b/.github/workflows/run-test.yml
--- a/.github/workflows/run-test.yml
+++ b/.github/workflows/run-test.yml
@@ -36,5 +36,5 @@ jobs:
         pip install -r requirements.txt
 
     - name: Run tests
-      run: pytest || cat log
+      run: BRANCH=${{ matrix.branch }} pytest || cat log && exit 1 # on error, show log and break
 
